databases:
  - name: recipeapp
    databaseName: recipeapp_f3hh
    user: recipeapp_f3hh_user

services:
  - type: web
    name: recipeApp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipeapp_f3hh
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false